# Generated by Django 3.1.7 on 2021-03-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicDetails',
        ),
        migrations.DeleteModel(
            name='PresentLocation',
        ),
    ]
